//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeaveAvaliability
    {
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public int LeaveTypeId { get; set; }
        public decimal AllocatedDays { get; set; }
        public decimal AvailedDays { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual LeaveType LeaveType { get; set; }
    }
}
